version: "3.8"

services:
  postgresdb:
#    container_name: mysqldb
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: papimaciano
#      MYSQL_DATABASE: socialmedia_db
#    networks:
#     springboot-mysql-net:mysqldb:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: lwsmlnkv
      POSTGRES_PASSWORD: fUqV5uZYpOsULi9v-ViWuVjMndsTrH9e
    networks:
     springboot-sql-net:

  springboot-socialmedia-api:
    container_name: springboot-socialmedia-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      springboot-sql-net:
    restart: on-failure

networks:
    springboot-sql-net:

