version: "3.8"

services:
  mysqldb:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: papimaciano
      MYSQL_DATABASE: socialmedia_db
    networks:
     springboot-mysql-net:

  springboot-socialmedia-api:
    container_name: socialmedia-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: papimaciano
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure


networks:
    springboot-mysql-net:

