version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: papimaciano
      MYSQL_DATABASE: socialmedia_db
    networks:
     springboot-mysql-net:

  springboot-socialmedia-api:
    container_name: springboot-socialmedia-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
    springboot-mysql-net:

